// https://registry.khronos.org/OpenGL/api/GL/glcorearb.h
X(void,   CreateBuffers,            (GLsizei n, GLuint *buffers))
X(void,   CreateVertexArrays,       (GLsizei n, GLuint *arrays))
X(void,   NamedBufferStorage,       (GLuint buffer, GLsizeiptr size, const void *data, GLbitfield flags))
X(void,   VertexArrayVertexBuffer,  (GLuint vaobj, GLuint bindingindex, GLuint buffer, GLintptr offset, GLsizei stride))
X(void,   VertexArrayAttribBinding, (GLuint vaobj, GLuint attribindex, GLuint bindingindex))
X(void,   VertexArrayAttribFormat,  (GLuint vaobj, GLuint attribindex, GLint size, GLenum type, GLboolean normalized, GLuint relativeoffset))
X(void,   EnableVertexArrayAttrib,  (GLuint vaobj, GLuint index))
X(GLuint, CreateShader,             (GLenum type))
X(void,   ShaderSource,             (GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length))
X(void,   CompileShader,            (GLuint shader))
X(void,   GetShaderiv,              (GLuint shader, GLenum pname, GLint *params))
X(void,   GetShaderInfoLog,         (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog))
X(GLuint, CreateProgram,            (void))
X(void,   AttachShader,             (GLuint program, GLuint shader))
X(void,   LinkProgram,              (GLuint program))
X(void,   GetProgramiv,             (GLuint program, GLenum pname, GLint *params))
X(void,   GetProgramInfoLog,        (GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog))
X(void,   DeleteShader,             (GLuint shader))
X(void,   BindVertexArray,          (GLuint array))
X(void,   UseProgram,               (GLuint program))
X(void,   Viewport,                 (GLint x, GLint y, GLsizei width, GLsizei height))
