// https://registry.khronos.org/OpenGL/api/GL/glcorearb.h
X(GLuint, CreateShader,            (GLenum type))
X(void,   ShaderSource,            (GLuint shader, GLsizei count, const GLchar* const* string, const GLint* length))
X(void,   CompileShader,           (GLuint shader))
X(void,   GetShaderiv,             (GLuint shader, GLenum pname, GLint* params))
X(void,   GetShaderInfoLog,        (GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* infoLog))
X(GLuint, CreateProgram,           (void))
X(void,   AttachShader,            (GLuint program, GLuint shader))
X(void,   LinkProgram,             (GLuint program))
X(void,   GetProgramiv,            (GLuint program, GLenum pname, GLint* params))
X(void,   GetProgramInfoLog,       (GLuint program, GLsizei bufSize, GLsizei* length, GLchar* infoLog))
X(void,   DeleteShader,            (GLuint shader))
X(void,   DeleteProgram,           (GLuint program))
X(void,   UseProgram,              (GLuint program))
X(void,   GenVertexArrays,         (GLsizei n, GLuint* arrays))
X(void,   BindVertexArray,         (GLuint array))
X(void,   DeleteVertexArrays,      (GLsizei n, const GLuint* arrays))
X(void,   GenBuffers,              (GLsizei n, GLuint* buffers))
X(void,   BindBuffer,              (GLenum target, GLuint buffer))
X(void,   BufferData,              (GLenum target, GLsizeiptr size, const void* data, GLenum usage))
X(void,   DeleteBuffers,           (GLsizei n, const GLuint* buffers))
X(void,   VertexAttribPointer,     (GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void* pointer))
X(void,   EnableVertexAttribArray, (GLuint index))
